version: '3'
services:
  nginx:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - backend
    volumes:
      - ./ibm_nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  backend:
    image: backend
    container_name: backend
    build:
      context: ./ibm_backend
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 443:443
    restart: on-failure